name: pizzacorn_widgets
description: "Customs Widgets by Pizzacorn."
version: 0.1.2
homepage: https://github.com/Pizzacorn/pizzacorn_customs
repository: https://github.com/Pizzacorn/pizzacorn_customs
issue_tracker: https://github.com/Pizzacorn/pizzacorn_customs/issues
topics:
  - widgets
  - ui
  - flutter

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0

flutter:
# Normalmente vacÃ­o en packages puros (sin assets).
